# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: G Roques
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Full stack developer with a passion for the web. See my portfolio and resume for more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "groques.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  gbroques

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

repository: gbroques/gbroques

encoding: utf-8

sass:
    style: compressed